### ISSUE TITLE
Duplicate rice in the first spring

### ISSUE THREAD

**Issue by unkenfaenger** [slothsoft/stardew-challenger#56]
![grafik](https://user-images.githubusercontent.com/16561195/196044114-439425a9-17d4-4e39-8330-4697565f176d.png)

If it matters, it was on the 18th of spring.

**Comment by slothsoft** [comment]
The problem here is that challenges were not stopped when the game returns to title.  So multiple instances of "add rice in the 1st spring" where registered here.
